server:
  port: 8003

#mybatis配置
mybatis:
  type-aliases-package: com.mc.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

#spring配置
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   #数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db03?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: mc123456

#Eureka配置，服务注册到哪里
#C:\Windows\System32\drivers\etc\hosts修改添加eureka7001.com，eureka7002.com，eureka7003.com
eureka:
  client:
    service-url:
#      defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-02-provider-dept-8003  #修改eureka上的默认描述信息!

#info配置
info:
  app.name: mc-springcloud
  company.name: blog.mc.study.com


