##k=v
##对空格的要求十分严格
##普通的key-vaLue
##注入到我们的配置类中
#
#name: qinjiang
##对象
#student:
#  name: qinjiang
#  age: 3
#
##行内写法
#student1: {name: qinjiang,age: 3}
#
##数组
#pet:
#  - cat
#  - dog
#  - pig
#
#pets: [cat,dog,pig]

person:
  name: qinjiang${random.uuid}
  age: ${random.int}
  happy: false
  birth: 2019/11/02
  maps: {k1: v1,k2: v2}
  hello: haha
  lists:
    - code
    - music
    - girl
  dog:
    name: ${person.hello:hello}_大黄
    age: 3

dog:
  first-name: 啊黄
  age: 3

server:
  port: 8080
spring:
  profiles:
    active: dev
---
server:
  port: 8081
spring:
  profiles: dev

---
server:
  port: 8082
spring:
  profiles: test

#可以通过 debug=true来查看，哪些自动配置类生效，哪些没有生效!
#debug: true
