server:
  port: 9527

spring:
  application:
    name: springcloud-zuul

#Eureka配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: zuul9527.com  #修改eureka上的默认描述信息!
    prefer-ip-address: true

zuul:
  routes:
    mydept.serviceId: springcloud-provider-dept
    mydept.path: /mydept/**
#  ignored-services: springcloud-provider-dept #不能再使用这个路径访问了. ignored :忽略
  ignored-services: "*" #ignored :忽略全部的~
  prefix: /mc  #设置公共的前缀


info:
  app.name: mc-springcloud
  company.name: blog.mcstudy.com

