server:
  port: 3344

spring:
  application:
    name: springcloud-13-config-server
  #连接远程仓库
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/Princekin_M/springcloud-config.git  #https ,不是git
